name: Pull Request

on: [pull_request]

jobs:
  Build:
    runs-on: macos-10.15
    timeout-minutes: 7
    steps:
      - name: "Setup Xcode 12.4"
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '12.4'
      - name: "Checkout Project"
        uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: "Cocoapods setup"
        run: pod update
      - name: "Build"
        run: xcodebuild -workspace AppExplorer.xcworkspace -scheme SoqlXplorer build CODE_SIGN_IDENTITY=-
      - name: "Test"
        run: xcodebuild -workspace AppExplorer.xcworkspace -scheme SoqlXplorer test CODE_SIGN_IDENTITY=-
