name: Pull Request

on: [pull_request]

jobs:
  Build:
    runs-on: macos-10.15
    timeout-minutes: 5
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: "Cocoapods setup"
        run: pod update
      - name: "Build"
        run: xcodebuild -workspace AppExplorer.xcworkspace -scheme SoqlXplorer
